site_name: GLPI 11 Enterprise Blueprint
site_description: Implantacao corporativa do GLPI 11 para uma empresa de servicos de tecnologia
site_author: Othon Santiago
repo_name: OthonSantiago/glpi-11-enterprise-blueprint
repo_url: https://github.com/OthonSantiago/glpi-11-enterprise-blueprint
theme:
  name: material
  language: pt-BR
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
    - search.suggest
    - search.highlight
markdown_extensions:
  - admonition
  - attr_list
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Inicio: index.md
  - Visao geral:
      - Escopo: 00-visao-geral/01-escopo.md
      - Roadmap: 00-visao-geral/02-roadmap.md
  - Arquitetura:
      - Entidades, grupos e perfis: 01-arquitetura/01-entidades-grupos-perfis.md
  - Fundacao GLPI:
      - Ordem de implementacao: 02-fundacao/01-ordem-implementacao.md
      - Formularios, regras e SLA: 02-fundacao/02-formularios-regras-sla.md
  - Catalogo:
      - Catalogo mestre: 03-catalogo/01-catalogo-mestre.md
  - Areas:
      - Visao geral: 04-areas/index.md
      - TI e Service Desk: 04-areas/01-ti-service-desk.md
      - Seguranca da Informacao: 04-areas/02-seguranca-informacao.md
